# Generated by Django 4.2.7 on 2023-11-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetFashionable', '0002_collection_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='image_height',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='design',
            name='image_width',
            field=models.IntegerField(default=200),
        ),
    ]
